version: '3'

services:
  cypress:
    ipc: host
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - "..:/workspace/cypress-devcontainer"
    environment:
      DISPLAY: ":14"
      LIBGL_ALWAYS_INDIRECT: 0
    volumes_from:
      - x11-bridge:rw
    depends_on:
      - x11-bridge

  x11-bridge:
    image: jare/x11-bridge
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    ports:
      - "8000:8000"
    restart: always
    environment:
      MODE: tcp
      XPRA_HTML: "yes"
      DISPLAY: ":14"
      XPRA_TCP_PORT: "8000"
      XPRA_PASSWORD: password
